# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: e2eTest

on:
  push:
  workflow_dispatch:
    inputs:
      env:
        description: 'environment'
        required: true
        type: choice
        default: 'PROD'
        options:
          - QA
          - STG
          - PROD
          
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: check event
      run: echo ${{ github.event_name }}
    - name: Run for push
      if: ${{ github.event_name }}  == 'push'
      run: mvn -Denv=QA clean install
    - name: Run for workflow
      if: ${{ github.event_name }}  == 'workflow_dispatch'
      run: mvn -Denv=${{ github.event.inputs.env }} clean install
